#!/usr/bin/env bash
#
# author: nov 2020
# cassio batista - https://cassota.gitlab.io

# pts: phonetic timestamp

if test $# -ne 2 ; then
    echo "usage: $0 <tg-in-dir> <pts-out-dir>"
    exit 1
elif [ ! -d "$1" ] ; then
    echo "error: textgrid dir must exist: '$1'"
    exit 1
fi

mkdir -p $2

rm -f /tmp/{p,ts}.tmp
for tg in $1/*.TextGrid ; do
    basefile=$(basename $tg)
    pts_file=$(echo $basefile | sed 's/\.TextGrid/\.pts/g')
    echo -ne "\r[$0] processing file $basefile"

    # get pts from falabrasil textgrid
    # https://unix.stackexchange.com/questions/21076/how-to-show-lines-after-each-grep-match-until-other-specific-match
    # TextGrid files generated by FalaBrasil aligner have 5 tier and the
    # phonemes happed to be in the first one, so we can't just grep around but
    # we can rather awk for two string to get the content in between them. As
    # we know the second tier stores phoneme syllabels under the name
    # "syllphones", awk will get everything from "phones" to "syllphones".
    # Beware theres a double space before the equal operator, this is Cassio's
    # fault and has to be the way it is.
    timestamps=$(awk '/name  = "phones"/,/name  = "syllphones"/' $tg |\
        grep 'xmax' | tail -n +2 | sed 's/xmax =//g' | tr -d '[ \t]')
    phonemes=$(awk '/name  = "phones"/,/name  = "syllphones"/' $tg |\
        grep 'text' | sed 's/text =//g' | tr -d '[ \t]')

    for p in $(echo $phonemes) ; do
        echo $p >> /tmp/p.tmp
    done
    for ts in $(echo $timestamps) ; do
        echo $ts >> /tmp/ts.tmp
    done

    paste /tmp/p.tmp /tmp/ts.tmp | expand -t 8 > $2/$pts_file
    rm -f /tmp/{p,ts}.tmp
done
echo
