#!/usr/bin/env bash
#
# author: nov 2020
# cassio batista - https://cassota.gitlab.io

# pts: phonetic timestamp
if test $# -ne 2 ; then
    echo "usage: $0 <tg-in-dir> <pts-out-dir>"
    exit 1
elif [ ! -d "$1" ] ; then
    echo "error: textgrid dir must exist: '$1'"
    exit 1
fi

mkdir -p $2

for gender in M F ; do
  rm -f /tmp/{p,ts}.tmp
  for tg in $1/$gender-*.TextGrid ; do
    basefile=$(basename $tg)
    pts_file=$(echo $basefile | sed 's/\.TextGrid/\.pts/g')
    echo -ne "\r[$0] processing file $basefile"

    # get pts from mfa textgrid
    # TextGrid files generated by MFA contain only two tiers and the phonemes
    # happen to be in the last one, so we'll just grep for the name of the tier
    # and if we're luck the entire phoneme set will be within the 500 next
    # lines so we can catch 'em all
    [ -f $tg ] || { echo -e "\n$0: no textgrid files in '$1'" && exit 1; }
    timestamps=$(grep 'name = "phones"' $tg -A 500 |\
        grep 'xmax' | tail -n +2 | sed 's/xmax =//g' | tr -d '[ \t]')
    phonemes=$(grep 'name = "phones"' $tg -A 500 |\
        grep 'text' | sed 's/text =//g' | tr -d '[ \t]')

    for p in $(echo $phonemes) ; do
        echo $p >> /tmp/p.tmp
    done
    for ts in $(echo $timestamps) ; do
        echo $ts >> /tmp/ts.tmp
    done

    paste /tmp/p.tmp /tmp/ts.tmp | expand -t 8 > $2/$pts_file
    rm -f /tmp/{p,ts}.tmp
  done
  echo
done
